import { addPossession, activePossession, ensureMaterialChildhood, roll as materialRoll } from "./material-core.js?v=1";
import { ensureHouseholdEconomy } from "./household-economy-v2.js?v=1";
import { ensureSchoolLifeV2 } from "./school-life-v2.js?v=1";

const clamp=(v,a=0,b=100)=>Math.max(a,Math.min(b,v));
const cash=v=>Math.max(0,Math.round(Number(v)||0));
const months=s=>Number(s.character?.ageMonths)||0;
const years=s=>Math.floor(months(s)/12);
const hash=v=>{let h=2166136261>>>0;for(const c of String(v??"")){h^=c.charCodeAt(0);h=Math.imul(h,16777619)>>>0;}h^=h>>>16;h=Math.imul(h,0x7feb352d)>>>0;h^=h>>>15;h=Math.imul(h,0x846ca68b)>>>0;return(h^(h>>>16))>>>0;};
const roll=(s,k)=>hash(`${Number(s.seed)||1}:${k}`)/4294967296;
const pick=(s,k,a)=>a[hash(`${s.seed}:${k}`)%a.length];
const first=p=>String(p?.name||"").split(" ")[0]||"someone";
const guardians=s=>(s.people||[]).filter(p=>["guardian","secondGuardian"].includes(p.role)&&!p.deceased);
const friends=s=>(s.people||[]).filter(p=>p.role==="friend"&&!p.deceased&&p.school?.friendshipStatus!=="former");

const PUBLIC_SECONDARY=["Rizal National High School","Mabini National High School","Malaya Integrated School","San Isidro National High School"];
const PRIVATE_SECONDARY=["St. Anne Academy","Brightwood Academy","Sacred Heart Academy","Northfield Academy"];
const TEACHERS=["Ms. Flores","Mr. Ramos","Ms. Lim","Mr. Navarro","Ms. Mendoza","Mr. Garcia","Ms. Reyes","Mr. Santos"];
const PEER_FIRST=["Maya","Liam","Zoe","Nina","Eli","Sam","Noah","Aya","Bea","Luis","Mika","Gab","Tala","Enzo","Rina","Nico","Inez","Joaquin","Celine","Marco"];
const LAST=["Reyes","Santos","Garcia","Cruz","Mendoza","Flores","Ramos","Lim","Tan","Navarro","Aquino","Villanueva"];

export function adolescenceStage(state){const a=years(state);if(a<13)return null;if(a<15)return"early";if(a<17)return"middle";return"late";}
export function teenGrade(age){if(age<=13)return"Grade 8";if(age===14)return"Grade 9";if(age===15)return"Grade 10";if(age===16)return"Grade 11";return"Grade 12";}
function uniqueName(state,salt){const existing=new Set((state.people||[]).map(p=>String(p.name||"").toLowerCase()));for(let i=0;i<40;i++){const name=`${PEER_FIRST[hash(`${state.seed}:${salt}:f:${i}`)%PEER_FIRST.length]} ${LAST[hash(`${state.seed}:${salt}:l:${i}`)%LAST.length]}`;if(!existing.has(name.toLowerCase()))return name;}return`Alex ${LAST[hash(`${state.seed}:${salt}:fallback`)%LAST.length]}`;}
function makeTeenPeer(state,index,role="classmate"){const name=uniqueName(state,`teen-peer-${index}`),id=`teen-${role}-${name.toLowerCase().replace(/[^a-z0-9]+/g,"-")}-${months(state)}`;return{id,role,relationshipLabel:role==="friend"?"Friend":"Classmate",name,sex:roll(state,`${id}:sex`)<.5?"Female":"Male",age:Math.floor(roll(state,`${id}:age`)*3)-1,introducedAtMonths:months(state),closeness:role==="friend"?52+Math.floor(roll(state,`${id}:close`)*10):30+Math.floor(roll(state,`${id}:close`)*16),trust:role==="friend"?48+Math.floor(roll(state,`${id}:trust`)*12):35+Math.floor(roll(state,`${id}:trust`)*14),affection:46+Math.floor(roll(state,`${id}:aff`)*15),conflict:5+Math.floor(roll(state,`${id}:conflict`)*14),familiarity:35+Math.floor(roll(state,`${id}:fam`)*18),lastInteractionAtMonths:months(state),history:[{ageMonths:months(state),date:{...(state.date||{})},eventId:"secondary_school_peer",note:`You met ${first({name})} around the start of secondary school.`}],school:{secondary:true,currentClass:true,friendshipStatus:role==="friend"?"friend":"acquaintance"},npc:{outsideStress:25+Math.floor(roll(state,`${id}:stress`)*25),availability:55+Math.floor(roll(state,`${id}:avail`)*25),socialWorld:45+Math.floor(roll(state,`${id}:social`)*30),currentThread:"Their own teenage life is unfolding alongside yours.",lastChangedAtMonths:months(state)}};}

function queue(state,item){const a=state.adolescence;if(!item?.key||a.seen.includes(item.key)||a.queue.some(x=>x.key===item.key))return;a.queue.push({priority:50,createdAtMonths:months(state),...item});a.queue.sort((x,y)=>(y.priority||0)-(x.priority||0)||(x.createdAtMonths||0)-(y.createdAtMonths||0));a.queue=a.queue.slice(0,14);}
export function queueAdolescenceEvent(state,item){ensureAdolescenceState(state);queue(state,item);}

function inheritedSelfEsteem(state){const d=state.character?.development||{},p=state.character?.personality||{};const psych=state.psychology?.dimensions||{};return clamp(Math.round((d.confidence??50)*.42+(psych.selfWorth??50)*.32+(100-(p.sensitivity??50))*.12+(d.attachment??50)*.14));}
function inheritedLoneliness(state){const social=state.childhood?.socialConfidence??50;const count=friends(state).length;const psych=state.psychology?.dimensions||{};return clamp(Math.round(56-social*.45-Math.min(18,count*5)+Math.max(0,55-(psych.socialSafety??55))*.32));}
function initialPhone(state){ensureMaterialChildhood(state);const material=state.material;const existing=activePossession(material,"phone");if(existing)return{owned:true,acquiredAtMonths:existing.acquiredAtMonths,quality:existing.quality,hasData:true,groupChats:0,screenConflict:0};const band=state.household.financeBand,r=roll(state,"teen-first-phone");const owned=band==="Comfortable"?r<.84:band==="Getting by"?r<.58:r<.24;if(owned){const price=band==="Comfortable"?9000:band==="Getting by"?5200:3200;const item=addPossession(state,"phone",band==="Tight"?"used smartphone":"smartphone","family purchase",price,band==="Comfortable"?80:68,18);return{owned:true,acquiredAtMonths:item.acquiredAtMonths,quality:item.quality,hasData:band!=="Tight"||roll(state,"teen-data")>.35,groupChats:0,screenConflict:0};}return{owned:false,acquiredAtMonths:null,quality:0,hasData:false,groupChats:0,screenConflict:0};}
function firstPeriodMonth(state){return 156+Math.floor(roll(state,"puberty-period-onset")*19);}
function voiceMonth(state){return 156+Math.floor(roll(state,"puberty-voice-onset")*19);}

function syncSecondaryInstitution(state,a){const profile=ensureSchoolLifeV2(state);if(!profile||a.education.secondarySynced)return;const mode=profile.mode,age=years(state);a.education.mode=mode;a.education.grade=teenGrade(age);a.education.secondarySynced=true;a.education.startedAtMonths=months(state);a.education.previousInstitution=profile.name;
  if(mode==="public"){profile.name=pick(state,"secondary-public-name",PUBLIC_SECONDARY);profile.otherMonthlyCost=cash((profile.otherMonthlyCost||700)+250);profile.annualFees=cash((profile.annualFees||1800)+900);}
  else if(mode==="private"){profile.name=pick(state,"secondary-private-name",PRIVATE_SECONDARY);profile.tuitionMonthly=cash((profile.tuitionMonthly||6500)*1.16);profile.otherMonthlyCost=cash((profile.otherMonthlyCost||1200)+450);profile.annualFees=cash((profile.annualFees||9000)*1.08);}
  else if(mode==="homeschool"){profile.name="Home study · Secondary level";profile.otherMonthlyCost=cash((profile.otherMonthlyCost||1800)*1.08);}
  profile.monthlyCost=cash((profile.tuitionMonthly||0)+(profile.otherMonthlyCost||0)+Math.round((profile.annualFees||0)/10));
  profile.enrollmentHistory||=[];profile.enrollmentHistory.push({ageMonths:months(state),mode:profile.mode,name:profile.name,reason:"secondary school transition"});profile.enrollmentHistory=profile.enrollmentHistory.slice(-12);
  a.education.institutionName=profile.name;a.education.tuitionMonthly=profile.tuitionMonthly||0;a.education.monthlyCost=profile.monthlyCost||0;a.education.classSize=profile.classSize||0;a.education.academicPressure=profile.academicPressure||50;
  if(["public","private"].includes(mode)){const oldIds=new Set(state.childhood?.school?.currentClassmateIds||[]);for(const person of state.people||[]){if(person.role==="teacher"){person.role="formerTeacher";person.relationshipLabel="Former teacher";if(person.school)person.school.currentTeacher=false;}if(oldIds.has(person.id)&&person.school)person.school.currentClass=false;}
    const start=hash(`${state.seed}:secondary-teacher-start`)%TEACHERS.length;a.education.teacherNames=[0,1,2,3].map(i=>TEACHERS[(start+i)%TEACHERS.length]);a.education.classmateIds=[];state.people||=[];for(let i=0;i<5;i++){const peer=makeTeenPeer(state,i,"classmate");state.people.push(peer);a.education.classmateIds.push(peer.id);}const existingFriends=friends(state);if(existingFriends.length){existingFriends.slice(0,2).forEach(p=>{p.school||={};p.school.secondary=true;p.school.currentClass=roll(state,`secondary-keep:${p.id}`)<.45;if(p.school.currentClass&&!a.education.classmateIds.includes(p.id))a.education.classmateIds.push(p.id);});}}
}

function initialState(state){const p=state.character?.personality||{},d=state.character?.development||{};const a={version:1,enteredAtMonths:months(state),stage:adolescenceStage(state),queue:[],seen:[],recentKinds:[],lastAdvancedAtMonths:months(state),lastOrdinaryAtMonths:-24,lastBirthdayYear:years(state),puberty:{progress:clamp(18+(years(state)-13)*20),bodyConfidence:clamp(Math.round((d.confidence??50)*.65+(100-(p.sensitivity??50))*.35)),growthSpurtSeen:false,acneSeen:false,periodOnsetMonths:state.character?.sex==="Female"?firstPeriodMonth(state):null,periodStarted:false,voiceOnsetMonths:state.character?.sex==="Male"?voiceMonth(state):null,voiceChanged:false},autonomy:{level:clamp(Math.round((d.autonomy??50)*.7+(p.independence??50)*.3)),curfewHour:20,privacy:state.material?.bedroom?.ownRoom?68:46,ruleConflict:0,commuteAlone:false,leftHomeAlone:true},identity:{selfEsteem:inheritedSelfEsteem(state),styleConfidence:clamp(Math.round((d.confidence??50)*.55+(p.independence??50)*.45)),values:[],ambition:null,questioning:28+Math.floor(roll(state,"identity-questioning")*25)},mental:{loneliness:inheritedLoneliness(state),coping:clamp(Math.round((d.emotionalRegulation??50)*.7+(d.attachment??50)*.3)),pressure:state.health?.stress??25,supportSeeking:state.psychology?.coping?.patterns?.helpSeeking?.score??35},phone:initialPhone(state),responsibility:{chores:45+Math.floor(roll(state,"teen-chores")*26),familyCare:guardians(state).length<=1?30:15,paidWork:null,lastPaidWorkAtMonths:null},education:{mode:null,grade:teenGrade(years(state)),institutionName:null,secondarySynced:false,teacherNames:[],classmateIds:[],academicPressure:50,lastGradeAge:years(state),lastChargedAtMonths:months(state),lastReviewAge:12,lastReentryReviewAge:12,track:null},social:{peerPressure:35+Math.floor(roll(state,"peer-pressure")*35),standing:state.childhood?.socialConfidence??50,onlineStanding:50,lastDramaAtMonths:-24},romance:{current:null,past:[],lastEventAtMonths:-24}};return a;}

export function ensureAdolescenceState(state){if(!state?.character||months(state)<156)return null;const fresh=!state.adolescence;state.adolescence||=initialState(state);if(fresh&&state.childhood?.eventQueue)state.childhood.eventQueue=[];const a=state.adolescence;a.queue||=[];a.seen||=[];a.recentKinds||=[];a.stage=adolescenceStage(state);a.education||=initialState(state).education;a.social||=initialState(state).social;a.romance||={current:null,past:[],lastEventAtMonths:-24};a.phone||=initialPhone(state);a.mental||={loneliness:inheritedLoneliness(state),coping:50,pressure:state.health?.stress??25,supportSeeking:35};a.identity||={selfEsteem:inheritedSelfEsteem(state),styleConfidence:50,values:[],ambition:null,questioning:35};a.autonomy||={level:50,curfewHour:20,privacy:50,ruleConflict:0,commuteAlone:false,leftHomeAlone:true};a.responsibility||={chores:50,familyCare:15,paidWork:null,lastPaidWorkAtMonths:null};a.puberty||=initialState(state).puberty;syncSecondaryInstitution(state,a);if(!a.seen.includes("adolescence-entry")&&!a.queue.some(x=>x.key==="adolescence-entry"))queue(state,{key:"adolescence-entry",type:"adolescence_entry",priority:100});return a;}

function chargeSecondary(state,a,elapsed,beforeAge){const p=ensureSchoolLifeV2(state);if(!p||!elapsed||p.mode==="out-of-school")return;const last=a.education.lastChargedAtMonths??beforeAge??months(state)-elapsed;if(last>=months(state))return;const chargeMonths=Math.min(elapsed,months(state)-last);if(chargeMonths<=0)return;ensureHouseholdEconomy(state);const due=cash((p.monthlyCost||0)*chargeMonths);let remaining=due;const savings=+state.household.savings||0;const from=Math.min(savings,remaining);state.household.savings=cash(savings-from);remaining-=from;if(remaining>0){state.household.economy.debt=cash((state.household.economy.debt||0)+remaining);if(p.mode==="private"){p.arrears=cash((p.arrears||0)+remaining);p.monthsBehind=Math.min(12,(p.monthsBehind||0)+chargeMonths);}}else if(p.mode==="private"&&p.arrears>0){p.arrears=cash(Math.max(0,p.arrears-due*.15));if(!p.arrears)p.monthsBehind=0;}a.education.lastChargedAtMonths=months(state);a.education.tuitionMonthly=p.tuitionMonthly||0;a.education.monthlyCost=p.monthlyCost||0;}
function syncGrade(state,a){const age=years(state),grade=teenGrade(age);if(a.education.grade!==grade){a.education.grade=grade;a.education.lastGradeAge=age;queue(state,{key:`teen-school-year:${age}`,type:"school_year_transition",priority:70,grade});}}
function updateInternalState(state,a,elapsed){const d=state.character?.development||{},p=state.character?.personality||{},mh=state.psychology?.mentalHealth;const impact=mh?.functionalImpact?.overall||0;a.puberty.progress=clamp(a.puberty.progress+elapsed*1.35);a.autonomy.level=clamp(a.autonomy.level+elapsed*.18+((p.independence??50)-50)*.002);a.identity.selfEsteem=clamp(a.identity.selfEsteem*.78+((d.confidence??50)*.55+(state.psychology?.dimensions?.selfWorth??50)*.45)*.22);a.mental.pressure=clamp((state.health?.stress??25)*.68+impact*.32);a.mental.loneliness=clamp(a.mental.loneliness*.76+inheritedLoneliness(state)*.24);a.social.standing=clamp(a.social.standing*.8+(state.childhood?.socialConfidence??50)*.2);}
function maybePuberty(state,a){const ageM=months(state);if(!a.puberty.growthSpurtSeen&&ageM>=158)queue(state,{key:"teen-growth-spurt",type:"growth_spurt",priority:68});if(!a.puberty.acneSeen&&ageM>=162&&roll(state,"teen-acne")<.68)queue(state,{key:"teen-acne",type:"acne",priority:54});if(state.character?.sex==="Female"&&!a.puberty.periodStarted&&ageM>=a.puberty.periodOnsetMonths)queue(state,{key:"teen-first-period",type:"first_period",priority:82});if(state.character?.sex==="Male"&&!a.puberty.voiceChanged&&ageM>=a.puberty.voiceOnsetMonths)queue(state,{key:"teen-voice-change",type:"voice_change",priority:64});}
function maybeAutonomy(state,a){const ageM=months(state);if(ageM>=160&&!a.seen.includes("teen-rules")&&!a.queue.some(x=>x.key==="teen-rules"))queue(state,{key:"teen-rules",type:"autonomy_rules",priority:72});if(ageM>=174&&!a.autonomy.commuteAlone&&["public","private"].includes(a.education.mode))queue(state,{key:"teen-commute-alone",type:"commute_alone",priority:55});}
function maybePhone(state,a){const ageM=months(state);if(!a.phone.owned&&ageM>=160&&!a.seen.includes("teen-phone-request"))queue(state,{key:"teen-phone-request",type:"phone_request",priority:67});else if(a.phone.owned&&ageM>=163&&!a.seen.includes("teen-group-chat"))queue(state,{key:"teen-group-chat",type:"group_chat",priority:58});}
function maybeIdentity(state,a){const ageM=months(state);if(ageM>=166&&!a.seen.includes("teen-style")&&!a.queue.some(x=>x.key==="teen-style"))queue(state,{key:"teen-style",type:"identity_style",priority:48});if(ageM>=184&&!a.seen.includes("teen-values"))queue(state,{key:"teen-values",type:"identity_values",priority:46});if(ageM>=192&&!a.seen.includes("teen-future-direction"))queue(state,{key:"teen-future-direction",type:"future_direction",priority:64});}
function maybeMental(state,a){const ageM=months(state);if(a.mental.pressure>=55&&ageM-(a.mental.lastSupportEventAtMonths??-30)>=12)queue(state,{key:`teen-overwhelmed:${Math.floor(ageM/12)}`,type:"overwhelmed",priority:76});}
function maybePeerPressure(state,a){const ageM=months(state);if(ageM>=168&&ageM-(a.social.lastPressureAtMonths??-24)>=18&&roll(state,`peer-pressure:${Math.floor(ageM/6)}`)<.42)queue(state,{key:`teen-peer-pressure:${Math.floor(ageM/6)}`,type:"peer_pressure",priority:57});}
function maybeSchool(state,a){const age=years(state),p=ensureSchoolLifeV2(state);if(!p)return;if(["public","private"].includes(p.mode)&&age>a.education.lastReviewAge){a.education.lastReviewAge=age;queue(state,{key:`teen-report-card:${age}`,type:"report_card",priority:60});const strongest=Math.max(...Object.values(state.education?.subjects||{}).map(Number),...Object.values(state.interests||{}).map(Number));if(strongest>=66&&roll(state,`teen-competition:${age}`)<.45)queue(state,{key:`teen-competition:${age}`,type:"competition",priority:51});}
if(p.mode==="private"&&((p.monthsBehind||0)>=2||(p.arrears||0)>(p.tuitionMonthly||0)*1.5))queue(state,{key:`teen-tuition-pressure:${age}`,type:"tuition_pressure",priority:88,forced:(p.monthsBehind||0)>=4});if(p.mode==="out-of-school"&&age>(a.education.lastReentryReviewAge??12)){a.education.lastReentryReviewAge=age;queue(state,{key:`teen-reentry:${age}`,type:"education_reentry",priority:84});}}
function maybeResponsibility(state,a){const ageM=months(state);if(ageM>=180&&!a.seen.includes("teen-family-responsibility"))queue(state,{key:"teen-family-responsibility",type:"family_responsibility",priority:52});if(ageM>=192&&!a.responsibility.paidWork&&!a.seen.includes("teen-part-time-work")){const tight=state.household.financeBand==="Tight",chance=tight?.76:.46;if(roll(state,"teen-work-offer")<chance)queue(state,{key:"teen-part-time-work",type:"part_time_work",priority:60});}}
function romanceCandidate(state,a){const ids=new Set(a.education.classmateIds||[]);const candidates=(state.people||[]).filter(p=>!p.deceased&&p.id&&((p.role==="friend"&&p.closeness>=44)||(ids.has(p.id)&&p.closeness>=34)));if(!candidates.length)return null;return candidates[hash(`${state.seed}:romance:${months(state)}`)%candidates.length];}
function maybeRomance(state,a){const ageM=months(state);if(ageM<174||ageM-(a.romance.lastEventAtMonths??-24)<18)return;if(a.romance.current)return;const person=romanceCandidate(state,a);if(person&&roll(state,`teen-romance:${Math.floor(ageM/6)}`)<.4)queue(state,{key:`teen-crush:${person.id}:${Math.floor(ageM/12)}`,type:"teen_crush",priority:50,personId:person.id});}
function ordinary(state,a){if(a.queue.length)return;if(months(state)-(a.lastOrdinaryAtMonths??-24)<3)return;const kinds=["ordinary_home","ordinary_identity","ordinary_friend","ordinary_school","ordinary_independence"].filter(k=>!(a.recentKinds||[]).includes(k));const pool=kinds.length?kinds:["ordinary_home","ordinary_identity","ordinary_friend","ordinary_school","ordinary_independence"];const type=pool[hash(`${state.seed}:ordinary:${months(state)}`)%pool.length];queue(state,{key:`teen-${type}:${months(state)}`,type,priority:20});a.lastOrdinaryAtMonths=months(state);}

export function advanceAdolescence(state,elapsed=0,beforeAgeMonths=null){const a=ensureAdolescenceState(state);if(!a||!elapsed||state.death)return state;chargeSecondary(state,a,elapsed,beforeAgeMonths);syncGrade(state,a);updateInternalState(state,a,elapsed);maybePuberty(state,a);maybeAutonomy(state,a);maybePhone(state,a);maybeIdentity(state,a);maybeMental(state,a);maybePeerPressure(state,a);maybeSchool(state,a);maybeResponsibility(state,a);maybeRomance(state,a);ordinary(state,a);a.lastAdvancedAtMonths=months(state);return state;}

export function markAdolescenceSeen(state,event){const a=ensureAdolescenceState(state);if(!a||!event)return;a.seen.push(event.adolescenceKey||event.id);a.seen=[...new Set(a.seen)].slice(-180);a.queue=a.queue.filter(x=>x.key!==(event.adolescenceKey||event.key));const kind=event.adolescenceType||event.type;if(kind){a.recentKinds=[kind,...(a.recentKinds||[]).filter(x=>x!==kind)].slice(0,3);}}
export function teenPerson(state,id){return(state.people||[]).find(p=>p.id===id)||null;}
export function addTeenPhone(state,source="family purchase",price=5200,quality=70){const a=ensureAdolescenceState(state);if(a.phone.owned)return a.phone;ensureMaterialChildhood(state);const item=addPossession(state,"phone",source==="used"?"used smartphone":"smartphone",source,price,quality,18);a.phone={owned:true,acquiredAtMonths:item.acquiredAtMonths,quality:item.quality,hasData:true,groupChats:0,screenConflict:0};return a.phone;}
export function switchTeenEducation(state,mode,reason){const a=ensureAdolescenceState(state),p=ensureSchoolLifeV2(state);if(!a||!p)return state;p.mode=mode;p.reason=reason||null;p.arrears=0;p.monthsBehind=0;if(mode==="public"){p.name=pick(state,`teen-public-${months(state)}`,PUBLIC_SECONDARY);p.tuitionMonthly=0;p.otherMonthlyCost=850;p.annualFees=2600;p.classSize=36;p.facilities=58;p.academicPressure=54;p.clubAccess=62;p.commuteMinutes=22;}else if(mode==="homeschool"){p.name="Home study · Secondary level";p.tuitionMonthly=0;p.otherMonthlyCost=2100;p.annualFees=0;p.classSize=1;p.facilities=60;p.academicPressure=48;p.clubAccess=34;p.commuteMinutes=0;}p.monthlyCost=cash((p.tuitionMonthly||0)+(p.otherMonthlyCost||0)+Math.round((p.annualFees||0)/10));p.enrollmentHistory||=[];p.enrollmentHistory.push({ageMonths:months(state),mode:p.mode,name:p.name,reason});a.education.mode=p.mode;a.education.institutionName=p.name;a.education.tuitionMonthly=p.tuitionMonthly||0;a.education.monthlyCost=p.monthlyCost||0;a.education.classSize=p.classSize||0;if(mode==="public"&&!a.education.classmateIds.length){state.people||=[];for(let i=0;i<5;i++){const peer=makeTeenPeer(state,20+i,"classmate");state.people.push(peer);a.education.classmateIds.push(peer.id);}}return state;}

export function adolescenceSnapshot(state){const a=ensureAdolescenceState(state);if(!a)return null;const p=ensureSchoolLifeV2(state);return{stage:a.stage,stageLabel:a.stage==="early"?"Early adolescence":a.stage==="middle"?"Middle adolescence":"Late adolescence",puberty:{...a.puberty},autonomy:{...a.autonomy},identity:{...a.identity},mental:{...a.mental},phone:{...a.phone},responsibility:{...a.responsibility},social:{...a.social},romance:{...a.romance},education:{...a.education,mode:p?.mode||a.education.mode,institutionName:p?.name||a.education.institutionName,tuitionMonthly:p?.tuitionMonthly||0,monthlyCost:p?.monthlyCost||0,arrears:p?.arrears||0,classSize:p?.classSize||0},friends:friends(state)};}
