import { adulthoodSnapshot, ensureAdulthoodState } from "./adulthood-core.js?v=1";

const STORAGE_KEY="little-days-save-v2";
let scheduled=false;
function read(){try{const s=JSON.parse(localStorage.getItem(STORAGE_KEY));if(!s?.character||(+s.character.ageMonths||0)<216)return null;ensureAdulthoodState(s);return s;}catch{return null;}}
function route(){return location.hash.replace(/^#/,"")||"life";}
function esc(v){return String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;");}
function peso(v){return`₱${Math.max(0,Math.round(Number(v)||0)).toLocaleString("en-PH")}`;}
function styles(screen){if(screen.querySelector("#adulthood-ui-styles"))return;screen.insertAdjacentHTML("afterbegin",`<style id="adulthood-ui-styles">.adult-card{margin:14px 0 18px;padding:12px 0;border-top:1px solid var(--line);border-bottom:1px solid var(--line)}.adult-card h2{margin:0;font-family:var(--serif);font-size:18px;font-weight:500}.adult-kicker{margin:0 0 3px;color:var(--muted);font-size:9px;font-weight:800;letter-spacing:.08em;text-transform:uppercase}.adult-copy{margin:5px 0 0;color:var(--muted);font-size:10px;line-height:1.5}.adult-grid{display:grid;grid-template-columns:1fr 1fr;gap:0 14px;margin-top:8px}.adult-fact{padding:8px 0;border-top:1px solid var(--line)}.adult-fact span{display:block;color:var(--muted);font-size:8px;text-transform:uppercase;letter-spacing:.06em}.adult-fact strong{display:block;margin-top:2px;font-family:var(--serif);font-size:13px;font-weight:500}.adult-note{margin:8px 0 0;padding:8px 10px;background:rgba(255,255,255,.18);border-left:2px solid var(--line-strong);font-size:10px;line-height:1.45}</style>`);}
function educationLabel(e){if(e.path==="university")return"College / university";if(e.path==="technical")return"Technical / vocational";if(e.path==="work")return"Working instead of formal study";if(e.path==="gap")return"Gap period";return"Deciding";}
function careerLabel(c){return c.status==="working"?(c.job?.title||"Working"):"Not currently working";}
function renderSelf(state,screen,a){screen.querySelector("[data-adolescence-self]")?.remove();if(screen.querySelector("[data-adulthood-self]"))return;const card=document.createElement("section");card.className="adult-card";card.dataset.adulthoodSelf="1";card.innerHTML=`<p class="adult-kicker">${esc(a.stageLabel)}</p><h2>Adult life</h2><p class="adult-copy">Your adult finances, education, work, housing and relationships now belong to your own life state rather than being extensions of your parents' household.</p><div class="adult-grid"><div class="adult-fact"><span>Current path</span><strong>${esc(educationLabel(a.education))}</strong></div><div class="adult-fact"><span>Work</span><strong>${esc(careerLabel(a.career))}</strong></div><div class="adult-fact"><span>Income</span><strong>${peso(a.finances.monthlyIncome)}/mo</strong></div><div class="adult-fact"><span>Expenses</span><strong>${peso(a.finances.monthlyExpenses)}/mo</strong></div><div class="adult-fact"><span>Housing</span><strong>${esc(a.housing.label)}</strong></div><div class="adult-fact"><span>Personal savings</span><strong>${peso(a.finances.savings)}</strong></div></div>${a.finances.personalDebt>0?`<p class="adult-note">Personal uncovered costs / debt: about ${peso(a.finances.personalDebt)}. This is separate from your parents' household debt.</p>`:""}${a.responsibilities.childIds?.length?`<p class="adult-note">You are supporting ${a.responsibilities.childIds.length} child${a.responsibilities.childIds.length===1?"":"ren"}. Childcare is part of your monthly adult expenses.</p>`:""}`;const anchor=screen.querySelector(".divider")||screen.querySelector(".page-title");if(anchor)anchor.insertAdjacentElement(anchor.classList.contains("divider")?"beforebegin":"afterend",card);else screen.appendChild(card);}
function renderHome(screen,a){screen.querySelector("[data-adolescence-home]")?.remove();if(screen.querySelector("[data-adulthood-home]"))return;const card=document.createElement("section");card.className="data-section";card.dataset.adulthoodHome="1";card.innerHTML=`<h3 class="data-heading">Your housing</h3><div class="data-row"><span class="label">Arrangement</span><span class="value">${esc(a.housing.label)}</span></div><div class="data-row"><span class="label">Rent</span><span class="value">${a.housing.rentMonthly?`${peso(a.housing.rentMonthly)}/mo`:"None"}</span></div><div class="data-row"><span class="label">Family contribution</span><span class="value">${a.housing.contributionMonthly?`${peso(a.housing.contributionMonthly)}/mo`:"None"}</span></div>`;const existing=[...screen.querySelectorAll(".data-section")].find(s=>/Home Life/i.test(s.querySelector(".data-heading")?.textContent||""));if(existing)existing.insertAdjacentElement("afterend",card);else screen.appendChild(card);}
function renderSchool(screen,a){screen.querySelector("[data-adolescence-school]")?.remove();screen.querySelector("[data-school-v2-card]")?.remove();if(screen.querySelector("[data-adulthood-education]"))return;const title=screen.querySelector(".page-title");if(title)title.textContent="Education";const table=screen.querySelector(".subject-table");if(table)table.style.display="none";for(const section of [...screen.querySelectorAll(".data-section")]){if(/Teacher|Current term|School lately/i.test(section.textContent||""))section.style.display="none";}const card=document.createElement("section");card.className="adult-card";card.dataset.adulthoodEducation="1";const status=a.education.completed?"Completed":a.education.status==="studying"||a.education.status==="training"?"In progress":a.education.status==="gap"?"On a gap period":"Not enrolled";card.innerHTML=`<p class="adult-kicker">Adult education</p><h2>${esc(educationLabel(a.education))}</h2><div class="adult-grid"><div class="adult-fact"><span>Status</span><strong>${esc(status)}</strong></div><div class="adult-fact"><span>Tuition</span><strong>${a.education.tuitionMonthly?`${peso(a.education.tuitionMonthly)}/mo`:"None"}</strong></div><div class="adult-fact"><span>Institution</span><strong>${esc(a.education.institution||"None currently")}</strong></div><div class="adult-fact"><span>Education debt</span><strong>${peso(a.education.debt||0)}</strong></div></div>`;if(title)title.insertAdjacentElement("afterend",card);else screen.appendChild(card);}
function renderCompleted(state,screen,a){if(!state.completed||(+state.character.ageMonths||0)<300)return;const age=screen.querySelector(".age-title");if(age)age.textContent="Age 25";const eyebrow=screen.querySelector(".eyebrow");if(eyebrow)eyebrow.textContent="Young adulthood foundation complete";const title=screen.querySelector(".event-title");if(title)title.textContent=`${state.character.firstName}'s young adulthood`;const copy=screen.querySelector(".event-copy");if(copy)copy.textContent=`By twenty-five, ${state.character.firstName} has carried childhood and adolescence into an adult life with real education, work, money, housing, relationships and responsibilities. Nothing at eighteen was reset just because the interface changed life stages.`;const note=screen.querySelector(".body-note");if(note)note.textContent=`The current adulthood foundation simulates ages 18–25. Current work: ${careerLabel(a.career)}. Current housing: ${a.housing.label}. Later adulthood is the next expansion.`;}
function render(){scheduled=false;const state=read(),screen=document.querySelector(".screen");if(!state||!screen)return;styles(screen);const a=adulthoodSnapshot(state);if(!a)return;const r=route();if(r==="self")renderSelf(state,screen,a);if(r==="home")renderHome(screen,a);if(r==="school")renderSchool(screen,a);if(r==="life")renderCompleted(state,screen,a);}
function schedule(){if(scheduled)return;scheduled=true;queueMicrotask(render);}if(typeof MutationObserver!=="undefined")new MutationObserver(schedule).observe(document.documentElement,{childList:true,subtree:true});window.addEventListener("hashchange",schedule);window.addEventListener("little-days-state-sync",schedule);if(document.readyState==="loading")window.addEventListener("DOMContentLoaded",schedule,{once:true});else schedule();