import { ensureMaterialChildhood, materialSnapshot } from "./material-childhood.js?v=1";

const STORAGE_KEY = "little-days-save-v2";
let scheduled = false;

function readState() {
  try {
    const state = JSON.parse(localStorage.getItem(STORAGE_KEY));
    if (!state?.character || !state?.household) return null;
    ensureMaterialChildhood(state);
    return state;
  } catch {
    return null;
  }
}
function escapeHtml(value){return String(value??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;");}
const peso=value=>`₱${Math.max(0,Math.round(Number(value)||0)).toLocaleString("en-PH")}`;
const route=()=>location.hash.replace(/^#/,"")||"life";
const age=state=>Math.floor((state.character?.ageMonths||0)/12);
function conditionWord(value){const n=Number(value)||0;return n>=82?"Newer":n>=62?"Good":n>=42?"Used":n>=24?"Worn":"Needs replacing";}
function allowanceLabel(money){if(money.allowanceMode==="regular")return`${peso(money.allowanceMonthly)} / month`;if(money.allowanceMode==="chores")return`Earned through chores · about ${peso(money.allowanceMonthly)} / month`;if(money.allowanceMode==="ask-as-needed")return"Ask as needed";return"No regular allowance";}
function styles(screen){if(screen.querySelector("#material-ui-styles"))return;screen.insertAdjacentHTML("afterbegin",`<style id="material-ui-styles">.material-section{margin-top:18px}.material-row{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:10px;padding:9px 0;border-top:1px solid var(--line);align-items:start}.material-row strong{display:block;font-family:var(--serif);font-size:13px;font-weight:500}.material-row p,.material-note{margin:2px 0 0;color:var(--muted);font-size:9px;line-height:1.45}.material-state{color:var(--muted);font-size:9px;text-align:right;white-space:nowrap}.material-money{display:grid;grid-template-columns:1fr 1fr;gap:8px}.material-money-card{border-top:1px solid var(--line);padding:9px 0}.material-money-card span{display:block;color:var(--muted);font-size:9px;text-transform:uppercase}.material-money-card strong{font-family:var(--serif);font-size:16px;font-weight:500}.material-history{padding:8px 0;border-top:1px solid var(--line);font-size:10px;line-height:1.45}.material-room-title{margin:0;font-family:var(--serif);font-size:18px;font-weight:500}.material-room-copy{margin:4px 0 0;font-size:11px;line-height:1.5}.material-chip{display:inline-block;margin:5px 5px 0 0;padding:3px 6px;border:1px solid var(--line);border-radius:999px;color:var(--muted);font-size:8px}</style>`);}
function home(state,screen,snapshot){if(screen.dataset.materialHome)return;const room=snapshot.bedroom,sections=[...screen.querySelectorAll(".data-section")],money=sections.find(x=>/household money/i.test(x.querySelector(".data-heading")?.textContent||"")),anchor=money||sections[sections.length-1]||screen;const roomEl=document.createElement("section");roomEl.className="data-section material-section";roomEl.innerHTML=`<h3 class="data-heading">Your space</h3><h4 class="material-room-title">${escapeHtml(room?.label||"Your sleeping space")}</h4><p class="material-room-copy">${room?.ownRoom?"You have a room mostly to yourself.":"Your sleeping space is shared with other people in the household."}</p>${(room?.decorations||[]).map(x=>`<span class="material-chip">${escapeHtml(x)}</span>`).join("")}`;const assetEl=document.createElement("section");assetEl.className="data-section material-section";assetEl.innerHTML=`<h3 class="data-heading">Things at home</h3>${snapshot.householdAssets.slice(0,8).map(x=>`<div class="material-row"><div><strong>${escapeHtml(x.label)}</strong><p>Part of everyday home life.</p></div><span class="material-state">${x.id==="internet"?"Connected":conditionWord(x.condition)}</span></div>`).join("")}`;const historyEl=document.createElement("section");historyEl.className="data-section material-section";historyEl.innerHTML=`<h3 class="data-heading">Home history</h3>${[...snapshot.moveHistory].slice(-4).reverse().map(x=>`<div class="material-history"><strong>${escapeHtml(x.housing||"Home")}</strong> · ${escapeHtml(x.tenure||"")}${x.reason?`<br><span style="color:var(--muted)">${escapeHtml(x.reason)}</span>`:""}</div>`).join("")}`;if(anchor.insertAdjacentElement){anchor.insertAdjacentElement("afterend",historyEl);anchor.insertAdjacentElement("afterend",assetEl);anchor.insertAdjacentElement("afterend",roomEl);}else screen.append(roomEl,assetEl,historyEl);screen.dataset.materialHome="1";}
function self(state,screen,snapshot){if(screen.dataset.materialSelf||age(state)<3)return;const things=document.createElement("section");things.className="material-section";const list=[...snapshot.possessions].sort((a,b)=>(b.sentimental||0)-(a.sentimental||0)).slice(0,10);things.innerHTML=`<h2 class="section-title">Your things</h2>${list.map(x=>`<div class="material-row"><div><strong>${escapeHtml(x.label)}</strong><p>${escapeHtml(x.source||"yours")} · around age ${Math.max(0,Math.floor((x.acquiredAtMonths||0)/12))}</p></div><span class="material-state">${conditionWord(x.condition)}</span></div>`).join("")}`;screen.appendChild(things);if(age(state)>=6){const m=snapshot.money,el=document.createElement("section");el.className="material-section";el.innerHTML=`<h2 class="section-title">Your money</h2><div class="material-money"><div class="material-money-card"><span>Cash</span><strong>${peso(m.cash)}</strong></div><div class="material-money-card"><span>Savings</span><strong>${peso(m.savings)}</strong></div></div><p class="material-note">${escapeHtml(allowanceLabel(m))}${m.savingsGoal?" · You are saving toward something you wanted.":""}</p>`;screen.appendChild(el);}screen.dataset.materialSelf="1";}
function render(){scheduled=false;const screen=document.querySelector(".screen");if(!screen)return;const state=readState();if(!state)return;const snapshot=materialSnapshot(state);styles(screen);if(route()==="home")home(state,screen,snapshot);else if(route()==="self")self(state,screen,snapshot);}
function schedule(){if(scheduled)return;scheduled=true;queueMicrotask(render);}
if(typeof MutationObserver!=="undefined")new MutationObserver(schedule).observe(document.documentElement,{childList:true,subtree:true});
window.addEventListener("hashchange",schedule);window.addEventListener("little-days-state-sync",schedule);if(document.readyState==="loading")window.addEventListener("DOMContentLoaded",schedule,{once:true});else schedule();
