import { ensureHouseholdEconomy } from "./household-economy-v2.js?v=1";

export const clamp=(v,a=0,b=100)=>Math.max(a,Math.min(b,v));
export const trendItems={school_bag:["school-bag","school bag",1650],tumbler:["tumbler","insulated tumbler",1250],white_sneakers:["shoes","white sneakers",2200],bag_charm:["bag-charm","bag charm",780],pencil_case:["pencil-case","pencil case",620],digital_watch:["watch","digital watch",1450],crossbody:["bag","crossbody bag",1800],earbuds:["earbuds","wireless earbuds",2600]};
export const assets={refrigerator:["refrigerator",15500,2800],television:["television",11500,1900],washing_machine:["washing machine",13500,2400],internet:["home internet",1800,900],computer:["family computer",22000,3200],aircon:["air conditioner",21000,3500],car:["family car",420000,14000]};
function hash(v){let h=2166136261>>>0;for(const c of String(v??"")){h^=c.charCodeAt(0);h=Math.imul(h,16777619)>>>0;}h^=h>>>16;h=Math.imul(h,0x7feb352d)>>>0;h^=h>>>15;return (Math.imul(h,0x846ca68b)^(h>>>16))>>>0;}
export const roll=(s,k)=>hash(`${s.seed||1}:${k}`)/4294967296;
export function rand(s){s.materialRngState||=((Number(s.seed)||1)^0x6c8e9cf5)>>>0;s.materialRngState=(Math.imul(s.materialRngState,1664525)+1013904223)>>>0;return s.materialRngState/4294967296;}
export const age=s=>Math.floor((s.character?.ageMonths||0)/12);
export const guardians=s=>(s.people||[]).filter(p=>["guardian","secondGuardian"].includes(p.role)&&!p.deceased);
export const siblings=s=>(s.people||[]).filter(p=>p.role==="sibling"&&!p.deceased&&p.family?.household!==false);
export const first=p=>String(p?.name||"your parent").split(" ")[0];
export function pushUpdate(s,category,text,importance=2){const x={category,text,importance,ageMonths:s.character.ageMonths,date:{...(s.date||{})},personId:null};s.worldEvents||=[];s.worldEvents.push({...x,note:text,source:"material-childhood"});s.worldEvents=s.worldEvents.slice(-120);s.realism||={};s.realism.latest||=[];s.realism.latest.push(x);s.realism.latest=s.realism.latest.sort((a,b)=>(b.importance||0)-(a.importance||0)).slice(0,8);}
export function spend(s,n){ensureHouseholdEconomy(s);n=Math.max(0,Math.round(n||0));s.household.economy.recentDiscretionarySpending=(s.household.economy.recentDiscretionarySpending||0)+n;const from=Math.min(s.household.savings||0,Math.round(n*.45));s.household.savings=Math.max(0,(s.household.savings||0)-from);}
function rawPossession(s,kind,label,source,value=0,quality=70,sentimental=15){return{id:`${kind}-${s.character.ageMonths}-${hash(`${kind}:${source}:${s.character.ageMonths}`)%99999}`,kind,label,source,value,quality,condition:clamp(quality+5),sentimental,acquiredAtMonths:s.character.ageMonths,active:true};}
function rawAdd(s,m,kind,label,source,value=0,quality=70,sentimental=15){if(["shoes","school-bag","pencil-case","watch","earbuds","bag","tumbler"].includes(kind))m.possessions.forEach(x=>{if(x.kind===kind&&x.active!==false)x.active=false;});const p=rawPossession(s,kind,label,source,value,quality,sentimental);m.possessions.push(p);m.possessions=m.possessions.slice(-40);return p;}
export function addPossession(s,kind,label,source,value=0,quality=70,sentimental=15){const m=ensureMaterialChildhood(s);return rawAdd(s,m,kind,label,source,value,quality,sentimental);}
export function activePossession(m,k){return [...m.possessions].reverse().find(x=>x.kind===k&&x.active!==false);}
function allowanceMode(s){const r=roll(s,"allowance"),b=s.household.financeBand;if(b==="Tight")return r<.25?"regular":r<.55?"chores":r<.9?"ask-as-needed":"none";if(b==="Comfortable")return r<.72?"regular":r<.88?"chores":"ask-as-needed";return r<.5?"regular":r<.72?"chores":r<.95?"ask-as-needed":"none";}
export function allowanceAmount(s,mode){const base=age(s)>=11?500:age(s)>=9?350:220,f=s.household.financeBand==="Comfortable"?1.45:s.household.financeBand==="Tight"?.7:1;return Math.round(base*f*(mode==="chores"?.75:1)/10)*10;}
export function roomArrangement(s){const beds=Math.max(1,Number(s.household.bedrooms)||1),kids=siblings(s);if(age(s)<2)return{kind:"parents",label:"Sleeping in your parents' room",ownRoom:false};if(beds<=1)return{kind:"family",label:"Shared family sleeping space",ownRoom:false};if(!kids.length)return{kind:"own",label:"Your own room",ownRoom:true};return{kind:"sibling",label:`Sharing a room with ${first(kids[0])}`,ownRoom:false};}
function initialAssets(s){const list=[{id:"refrigerator",condition:70},{id:"television",condition:68}];if(s.household.financeBand!=="Tight"||roll(s,"washer")>.5)list.push({id:"washing_machine",condition:72});if(age(s)>=5||s.household.financeBand==="Comfortable")list.push({id:"internet",condition:90});if(s.household.financeBand==="Comfortable"&&roll(s,"aircon")>.55)list.push({id:"aircon",condition:74});return list.map(x=>({...x,label:assets[x.id][0],active:true}));}
function seedThings(s,m){const a=age(s);if(!m.possessions.length)m.possessions.push(rawPossession(s,"keepsake","baby blanket","family",350,68,72));if(a>=2&&!activePossession(m,"shoes"))rawAdd(s,m,"shoes","everyday shoes","family purchase",650,68);if(a>=4&&!activePossession(m,"toy"))rawAdd(s,m,"toy","favorite toy","gift",500,66,55);if(a>=5&&!activePossession(m,"school-bag"))rawAdd(s,m,"school-bag","school bag","family purchase",850,70);if(a>=5&&!activePossession(m,"pencil-case"))rawAdd(s,m,"pencil-case","pencil case","family purchase",240,64);}
export function syncTrendPossessions(s){const m=s.material;if(!m)return;for(const x of s.childhood?.trends?.owned||[]){const d=trendItems[x.id];if(!d)continue;const src=`trend:${x.id}:${x.version||"popular"}`;if(m.possessions.some(p=>p.source===src))continue;rawAdd(s,m,d[0],`${x.version==="cheaper"?"budget":"popular"} ${d[1]}`,src,x.version==="cheaper"?Math.round(d[2]*.4):d[2],x.version==="cheaper"?65:82,28);}}
export function ensureMaterialChildhood(s){if(!s?.character||!s?.household)return null;ensureHouseholdEconomy(s);s.money||={savings:0};s.money.cash??=0;s.money.savings??=0;s.material||={version:1,possessions:[],householdAssets:initialAssets(s),pending:[],seen:[],bedroom:null,allowance:null,lastHousing:s.household.housing,lastCity:s.household.city,lastMoveCount:s.household.moveHistory?.length||0,lastAssetAt:-30,lastWornAt:-24,lastBirthdayAge:age(s)};const m=s.material;m.possessions||=[];m.householdAssets||=initialAssets(s);m.pending||=[];m.seen||=[];seedThings(s,m);if(!m.bedroom)m.bedroom={...roomArrangement(s),lastChangedAtMonths:s.character.ageMonths,decorations:[],history:[]};if(!m.allowance){const mode=allowanceMode(s);m.allowance={mode,monthlyAmount:allowanceAmount(s,mode),announced:age(s)<6,savingsRate:.45,totalReceived:0,birthdayMoney:0,lastBand:s.household.financeBand};}syncTrendPossessions(s);return m;}
export function queueMaterial(s,item){const m=ensureMaterialChildhood(s),key=item.key||`${item.type}:${s.character.ageMonths}`;if(m.seen.includes(key)||m.pending.some(x=>x.key===key))return;m.pending.push({priority:40,createdAtMonths:s.character.ageMonths,...item,key});m.pending=m.pending.sort((a,b)=>(b.priority||0)-(a.priority||0)).slice(0,10);}
export function replacementOutcome(s,item,premium=false){ensureHouseholdEconomy(s);const base=item.kind==="shoes"?900:item.kind==="school-bag"?850:280,target=premium?Math.round(base*2.4):base,room=Math.max(0,s.household.economy.monthlyDisposable||0)+Math.max(0,(s.household.savings||0)/20);if(s.household.financeBand==="Comfortable"&&room>target*1.4)return{kind:"new",price:target,quality:premium?88:80};if(s.household.financeBand!=="Tight"&&room>target)return{kind:"new",price:target,quality:premium?82:74};if(room>base*.55)return{kind:"budget",price:Math.round(base*.55),quality:62};return siblings(s).length&&item.kind!=="pencil-case"?{kind:"hand-me-down",price:0,quality:54}:{kind:"wait",price:0,quality:item.condition};}
export function replacePossession(s,item,o,premium=false){if(!item||o.kind==="wait")return;spend(s,o.price);const label=o.kind==="hand-me-down"?`hand-me-down ${item.kind}`:premium?`popular ${item.kind}`:`new ${item.kind}`;addPossession(s,item.kind,label,o.kind,o.price,o.quality,premium?24:12);}
export function materialSnapshot(s){const m=ensureMaterialChildhood(s);return{possessions:m.possessions.filter(x=>x.active!==false).map(x=>({...x})),householdAssets:m.householdAssets.filter(x=>x.active!==false).map(x=>({...x})),bedroom:{...m.bedroom},money:{cash:Math.round(s.money.cash||0),savings:Math.round(s.money.savings||0),savingsGoal:s.money.savingsGoal||null,allowanceMode:m.allowance.mode,allowanceMonthly:m.allowance.monthlyAmount,allowanceTotalReceived:m.allowance.totalReceived},moveHistory:[...(s.household.moveHistory||[])]};}