const clamp=(v,a=0,b=100)=>Math.max(a,Math.min(b,v));
function seeded(seed){let v=seed>>>0;return()=>{v=(v*1664525+1013904223)>>>0;return v/4294967296}}
function pick(r,a){return a[Math.floor(r()*a.length)]}
function between(r,a,b){return Math.round(a+r()*(b-a))}
function rand(s){s.realismRngState=(s.realismRngState*1664525+1013904223)>>>0;return s.realismRngState/4294967296}
function access(band,r){return clamp((band==="Comfortable"?78:band==="Getting by"?59:39)+between(r,-12,12),20,92)}
function congenital(r){if(r()>=.018)return null;return pick(r,[
{id:"hearing",label:"hearing impairment",known:false,at:between(r,8,36)},
{id:"vision",label:"visual impairment",known:false,at:between(r,18,54)},
{id:"heart",label:"congenital heart condition",known:true,at:0},
{id:"motor",label:"motor disability",known:false,at:between(r,8,30)},
{id:"developmental",label:"developmental condition",known:false,at:between(r,24,72)}])}
function profile(s,r){return{familyHistory:{cardiovascular:r()<.2,diabetes:r()<.18,mood:r()<.14,addiction:r()<.12,neurodevelopmental:r()<.08},constitution:between(r,42,78),healthcareAccess:access(s.household.financeBand,r),nutrition:clamp((s.household.financeBand==="Tight"?48:s.household.financeBand==="Getting by"?65:78)+between(r,-10,10)),environment:clamp((s.household.comfort==="Basic"?55:72)+between(r,-10,10)),congenital:congenital(r),congenitalKnown:false,active:[],chronic:[],disabilities:[],mental:{wellbeing:between(r,62,82),symptoms:null,recognized:false,support:null},latest:[],birthday:null}}
function ensureNpc(s,p,r){p.npc||={};if(p.npc.realism)return;const guardian=["guardian","secondGuardian"].includes(p.role),adult=guardian||p.role==="grandmother";let issue=null;if(guardian&&r()<.025)issue={kind:pick(r,["alcohol","gambling","substances"]),severity:1,months:between(r,1,18),visible:false};p.npc.realism={health:adult?between(r,58,84):between(r,68,90),mental:between(r,52,82),copingRisk:guardian?clamp(between(r,5,28)+(s.realism?.familyHistory?.addiction?12:0)):between(r,2,12),issue,employment:guardian?{status:r()<.08?"unemployed":r()<.12?"self-employed":"employed",stability:between(r,42,84),hours:between(r,32,52)}:null,major:null}}
export function ensureRealismState(s){if(!s?.character||!s?.household)return s;const seed=((Number(s.seed)||1)^0xa53c91e5)>>>0,r=seeded(seed||1);s.realismRngState||=(seed^0x6d2b79f5)>>>0;s.realism||=profile(s,r);s.realism.latest||=[];s.realism.active||=[];s.realism.chronic||=[];s.realism.disabilities||=[];s.realism.mental||={wellbeing:70,symptoms:null,recognized:false,support:null};s.worldEvents||=[];(s.people||[]).forEach(p=>ensureNpc(s,p,r));const c=s.realism.congenital;if(c?.known&&!s.realism.congenitalKnown){s.realism.congenitalKnown=true;s.realism.chronic.push({id:c.id,label:c.label,since:0,congenital:true})}return s}
function update(s,category,text,importance=1,p=null){const u={category,text,importance,ageMonths:s.character.ageMonths,date:{...s.date},personId:p?.id||null};s.realism.latest.push(u);s.worldEvents.push({...u,note:text,source:"realism"});s.worldEvents=s.worldEvents.slice(-40);if(p){p.npc.currentThread=text;p.npc.lastChangedAtMonths=s.character.ageMonths}}
function guardians(s){return(s.people||[]).filter(p=>["guardian","secondGuardian"].includes(p.role))}
function discover(s){const c=s.realism.congenital;if(!c||s.realism.congenitalKnown||s.character.ageMonths<c.at)return;s.realism.congenitalKnown=true;s.realism.chronic.push({id:c.id,label:c.label,since:s.character.ageMonths,congenital:true});update(s,"Health",`After a series of checkups, your family learns that you have a ${c.label}. It becomes part of the practical reality of growing up, not the whole story of who you are.`,3)}
function simulateGuardians(s,m){for(const p of guardians(s)){const r=p.npc.realism,first=p.name.split(" ")[0],stress=p.npc.outsideStress??35;r.mental=clamp(r.mental+Math.round((rand(s)-.55)*5)-(stress>70?2:0));if(r.employment){if(r.employment.status==="employed"&&rand(s)<(100-r.employment.stability)*.00018*m){r.employment.status="unemployed";s.household.financeBand=s.household.financeBand==="Comfortable"?"Getting by":"Tight";s.health.stress=clamp(s.health.stress+5);update(s,"Family",`${first} lost their job. Money at home becomes more uncertain while the adults figure out what comes next.`,3,p)}else if(r.employment.status==="unemployed"&&rand(s)<.055*m){r.employment.status="employed";if(s.household.financeBand==="Tight"&&rand(s)<.55)s.household.financeBand="Getting by";update(s,"Family",`${first} found work. The household does not transform overnight, but there is a little more room to breathe.`,2,p)}}if(!r.issue){const sf=stress>70?2.4:stress>55?1.5:.8;if(rand(s)<(r.copingRisk/100)*.0015*m*sf)r.issue={kind:pick(()=>rand(s),["alcohol","gambling","substances"]),severity:1,months:0,visible:false}}else{const i=r.issue;i.months+=m;if(rand(s)<(stress>65?.045:.018)*m&&i.severity<3)i.severity++;else if(rand(s)<(r.mental>65?.035:.012)*m&&i.severity>1)i.severity--;if(!i.visible&&(i.months>=4||i.severity>=2)&&rand(s)<.45){i.visible=true;const t=i.kind==="alcohol"?`${first} has been drinking more often lately. The change is becoming noticeable at home.`:i.kind==="gambling"?`${first} has been spending more time and money gambling. It has started to affect the household.`:`${first} has been relying on substances more often. The adults around you are beginning to notice that something is wrong.`;update(s,"Family",t,3,p)}if(i.visible&&i.severity>=2){s.health.stress=clamp(s.health.stress+2);s.household.savings=Math.max(0,(s.household.savings||0)-Math.round(350*m*i.severity));if(s.household.savings<1500)s.household.financeBand="Tight"}if(rand(s)<.008*m*(i.severity===1?2:1)){r.issue=null;if(i.visible)update(s,"Family",`${first} has started getting help. Recovery is not perfectly straight, but home life is beginning to change.`,3,p)}}}}
function delay(s){return clamp((s.household.financeBand==="Tight"?.24:s.household.financeBand==="Getting by"?.08:.02)+(55-s.realism.healthcareAccess)/180,.01,.5)}
function addIllness(s,severity){const label=severity>=3?(rand(s)<.5?"serious respiratory infection":"severe infection"):(rand(s)<.55?"respiratory infection":"stomach illness"),c={id:`ill-${s.character.ageMonths}-${Math.floor(rand(s)*99999)}`,label,severity,months:0,delayed:rand(s)<delay(s)};s.realism.active.push(c);if(severity>=3)update(s,"Health",`You become seriously ill with a ${label}. Your family is frightened enough that the illness changes the rhythm of the household.`,4);else update(s,"Health","You get sick enough that your usual routine stops for a while.",2);if(c.delayed&&severity>=2)update(s,"Money","Your family waits longer than they would like before getting medical care. Cost and practical access are part of the reason.",3)}
function consequence(s){const c=pick(()=>rand(s),[{id:"hearing-acquired",label:"lasting hearing loss",kind:"disability"},{id:"mobility-acquired",label:"a lasting mobility impairment",kind:"disability"},{id:"respiratory-acquired",label:"a chronic respiratory condition",kind:"chronic"}]);if(c.kind==="chronic")s.realism.chronic.push({...c,since:s.character.ageMonths});else s.realism.disabilities.push({...c,since:s.character.ageMonths});s.health.wellbeing=clamp(s.health.wellbeing-8);update(s,"Health",`You recover, but not exactly to where you were before. The illness leaves you with ${c.label}. Your family begins learning what needs to change and what does not.`,4)}
function die(s,cause){s.death={ageMonths:s.character.ageMonths,date:{...s.date},cause};s.completed=true;s.currentEventId=null;s.resolution=null;update(s,"Health","Your condition became too severe for your body to recover from.",5)}
function physical(s,m){if(s.death)return;const r=s.realism,age=Math.floor(s.character.ageMonths/12),v=clamp((65-r.constitution)/100+(55-r.nutrition)/180+(55-r.environment)/220,-.1,.7);if(!r.active.length){const moderate=clamp((.018+Math.max(0,v)*.018)*m,.01,.22),severe=clamp((.00035+Math.max(0,v)*.00055)*m*(age<2?1.45:1),.0002,.015),roll=rand(s);if(roll<severe)addIllness(s,3);else if(roll<severe+moderate)addIllness(s,2)}const keep=[];for(const c of r.active){c.months+=m;const care=c.delayed?r.healthcareAccess-20:r.healthcareAccess,recovery=clamp((c.severity===2?.55:.2)+(r.constitution-55)/180+(care-50)/220,.08,.9);if(rand(s)<recovery){if(c.severity>=3)update(s,"Health","After a frightening stretch of illness, you begin to recover.",3);s.health.wellbeing=clamp(s.health.wellbeing+3);continue}if(c.severity===2&&rand(s)<.12*m){c.severity=3;update(s,"Health","The illness gets worse instead of better. Your family seeks more help as your condition becomes serious.",4)}if(c.severity>=3){const df=c.delayed?1.9:1;if(rand(s)<.008*m*df*(1+Math.max(0,v)))consequence(s);if(rand(s)<.00055*m*df*(1+Math.max(0,v)*1.8)){die(s,c.label);return}}keep.push(c)}r.active=keep}
function adversity(s){let x=s.household.financeBand==="Tight"?12:s.household.financeBand==="Getting by"?4:0;for(const p of guardians(s)){const r=p.npc.realism;if(r?.issue?.visible)x+=r.issue.severity*9;if((p.npc.outsideStress??0)>70)x+=7;if(r?.employment?.status==="unemployed")x+=8}return x}
function mental(s,m){if(s.death||s.character.ageMonths<72)return;const h=s.realism.mental,friend=(s.people||[]).find(p=>p.role==="friend"),attach=s.character.development?.attachment??55,protect=(attach>68?4:0)+(friend?.closeness>70?4:0),pressure=adversity(s)+Math.max(0,s.health.stress-45)*.35;h.wellbeing=clamp(h.wellbeing+Math.round((rand(s)-.48)*5-pressure/18+protect/3));if(!h.symptoms&&h.wellbeing<40&&rand(s)<.045*m){h.symptoms={kind:rand(s)<.58?"anxiety":"low mood",months:0};h.recognized=false;s.health.stress=clamp(s.health.stress+5);update(s,"Health",h.symptoms.kind==="anxiety"?"Worry has started showing up more often, even when you cannot always explain what it is attached to.":"For a while now, things that usually interest you have felt flatter and harder to reach.",3)}if(!h.symptoms)return;h.symptoms.months+=m;if(!h.recognized&&h.symptoms.months>=4&&guardians(s).some(p=>(p.npc.availability??60)>55)&&rand(s)<.18*m){h.recognized=true;update(s,"Family","An adult who knows you well notices that you have not seemed like yourself lately. What you are feeling is finally spoken about.",3)}if(h.recognized&&!h.support&&rand(s)<(s.realism.healthcareAccess/100)*.08*m){h.support="counseling";update(s,"Health","You begin getting support for how you have been feeling. It does not make everything disappear, but you are no longer carrying it alone.",3)}if(rand(s)<(h.support?.16:.07)*m){h.wellbeing=clamp(h.wellbeing+10);if(h.wellbeing>58){h.symptoms=null;h.recognized=false;h.support=null;update(s,"Health","Your emotional health has been steadier lately. Difficult feelings have not vanished, but they are taking up less of the room.",2)}}}
function otherPeople(s,m){const age=Math.floor(s.character.ageMonths/12);for(const p of s.people||[]){if(p.deceased||p.introducedAtMonths>s.character.ageMonths||!["guardian","secondGuardian","grandmother","sibling"].includes(p.role))continue;const r=p.npc.realism,a=p.age+age;if(!r.major){const chance=(a>=70?.003:a>=55?.0012:a>=35?.00035:.00012)*m;if(rand(s)<chance){r.major={months:0,severity:rand(s)<.2?3:2};update(s,"Family",`${p.name.split(" ")[0]} has developed a health problem that now requires more appointments and rest than before.`,3,p)}}else{r.major.months+=m;if(rand(s)<(a<65?.09:.045)*m){r.major=null;update(s,"Family",`${p.name.split(" ")[0]}'s health has improved enough that family life is beginning to feel more normal again.`,2,p)}else if(r.major.severity>=3&&rand(s)<(a>=80?.007:a>=70?.003:.00035)*m){p.deceased=true;p.diedAtAge=a;s.health.stress=clamp(s.health.stress+14);update(s,"Family",`${p.name.split(" ")[0]} died after a period of poor health. Their absence changes routines that had once seemed permanent.`,5,p)}}}}
function birthday(s,before){const old=Math.floor(before/12),now=Math.floor(s.character.ageMonths/12);if(now<=old||now<=0)return null;let items=s.worldEvents.filter(e=>e.ageMonths>Math.max(0,s.character.ageMonths-12)).sort((a,b)=>(b.importance||0)-(a.importance||0)).slice(0,4).map(e=>e.text||e.note).filter(Boolean);if(!items.length)items=["Most of the year passed in ordinary routines, which is how a surprising amount of childhood is actually made."];return{age:now,items}}
export function advanceRealism(s,m,before){ensureRealismState(s);if(!m||m<0)return s;s.realism.latest=[];s.realism.birthday=null;discover(s);simulateGuardians(s,m);physical(s,m);if(!s.death){mental(s,m);otherPeople(s,m)}s.realism.healthcareAccess=clamp(s.realism.healthcareAccess+(s.household.financeBand==="Tight"?-1:s.household.financeBand==="Comfortable"?1:0));s.realism.latest=s.realism.latest.sort((a,b)=>b.importance-a.importance).slice(0,4);s.realism.birthday=birthday(s,before??Math.max(0,s.character.ageMonths-m));return s}
export function getAroundYou(s){ensureRealismState(s);return s.realism.latest||[]}
export function getBirthdayRecap(s){ensureRealismState(s);return s.realism.birthday}
export function healthSnapshot(s){ensureRealismState(s);const r=s.realism,known=[...r.chronic.map(x=>x.label),...r.disabilities.map(x=>x.label)],active=r.active[0]?.label||null,h=r.mental;let emotional="No major emotional-health concern has been recognized.";if(h.symptoms&&!h.recognized)emotional=h.symptoms.kind==="anxiety"?"You have been dealing with more worry than usual, though nobody has put a formal name to it.":"Your mood has been lower for a while, though nobody has put a formal name to it.";if(h.symptoms&&h.recognized)emotional=h.support?"People around you have noticed you are struggling, and you are receiving support.":"People around you have noticed that you are struggling emotionally.";return{physical:active?`You are currently dealing with a ${active}.`:known.length?`Your health includes ${known.join(", ")}.`:"No lasting physical condition is currently known.",known,active,emotional,care:r.healthcareAccess>=72?"Good access":r.healthcareAccess>=52?"Usually accessible":r.healthcareAccess>=36?"Sometimes difficult":"Limited",disabilities:r.disabilities}}
export function deathSummary(s){ensureRealismState(s);const a=s.death?.ageMonths??s.character.ageMonths,y=Math.floor(a/12),m=a%12,age=y?`${y} year${y===1?"":"s"}${m?` and ${m} month${m===1?"":"s"}`:""}`:`${m} month${m===1?"":"s"}`,closest=[...(s.people||[])].filter(p=>p.introducedAtMonths<=a).sort((x,z)=>(z.closeness||0)-(x.closeness||0))[0],mem=(s.memories||[]).slice(-2).map(x=>x.title.toLowerCase()),parts=[];if(closest)parts.push(`${closest.name} was one of the people closest to you.`);parts.push(mem.length?`Your life already contained memories of ${mem.join(" and ")}.`:"Most of your life was made of ordinary routines, familiar rooms, and people learning who you were.");return{title:`${s.character.firstName}'s life`,copy:`You lived for ${age}. ${parts.join(" ")} There is no score for a life ending early. It was still a life that happened to other people, and to you.`,cause:s.death?.cause||"illness"}}
